name: django-oidc-identity

services:
  dev:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    image: cdt/django-oidc-identity:dev
    env_file: .env
    # https://code.visualstudio.com/docs/remote/create-dev-container#_use-docker-compose
    entrypoint: sleep infinity
    volumes:
      - ./:/home/cdt/src
