name: Publish release

on:
  workflow_dispatch:
  push:
    tags:
      - "202[5-9].[0-9][0-9].[0-9]+"
      - "202[5-9].[0-9][0-9].[0-9]+-rc[0-9]+"

defaults:
  run:
    shell: bash

jobs:
  tests:
    uses: ./.github/workflows/tests-pytest.yml

  release:
    runs-on: ubuntu-latest
    environment: release
    needs: tests
    permissions:
      # https://github.com/softprops/action-gh-release#permissions
      contents: write
      # IMPORTANT: this permission is mandatory for Trusted Publishing
      # https://docs.pypi.org/trusted-publishers/using-a-publisher/
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          fetch-tags: true

      - uses: actions/setup-python@v6
        with:
          python-version: "3.11"
          cache: pip
          cache-dependency-path: "**/pyproject.toml"

      - name: Install build dependencies
        run: pip install build

      - name: Build package
        run: python -m build

      - name: Publish to Test PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        if: ${{ contains(github.ref, '-rc') }}
        with:
          repository_url: https://test.pypi.org/legacy/
          print_hash: true
          skip_existing: true
          verbose: true

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        if: ${{ !contains(github.ref, '-rc') }}
        with:
          print_hash: true

      - name: Output package info
        id: package
        run: |
          echo "VERSION=$(git describe)" >> "$GITHUB_OUTPUT"
          echo "PACKAGE=django-cdt-identity" >> "$GITHUB_OUTPUT"
          echo "PYPI=https://pypi.org/project/" >> "$GITHUB_OUTPUT"
          echo "TEST_PYPI=https://test.pypi.org/project/" >> "$GITHUB_OUTPUT"

      - name: Summarize package info
        id: summary
        env:
          VERSION: ${{ steps.package.outputs.VERSION }}
          PACKAGE: ${{ steps.package.outputs.PACKAGE }}
          PYPI: ${{ !contains(github.ref, '-rc') && steps.package.outputs.PYPI || steps.package.outputs.TEST_PYPI }}
        run: |
          url="$PYPI/$PACKAGE/$VERSION"
          echo "$url" >> $GITHUB_STEP_SUMMARY
          echo "PACKAGE_URL=$url" >> "$GITHUB_OUTPUT"

      - name: Release
        uses: softprops/action-gh-release@v2
        if: ${{ !contains(github.ref, '-rc') }}
        env:
          PACKAGE_URL: ${{ steps.summary.outputs.PACKAGE_URL }}
        with:
          files: |
            ./dist/*.tar.gz
            ./dist/*.whl
          prerelease: false
          generate_release_notes: true
          body: ${{ env.PACKAGE_URL }}
